### PR TITLE
Single Occupancy - Reserved

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by chrisns** [comment]
FYI @j1a1c1k

**Comment by j1a1c1k** [comment]
@chrisns Fine with that. I think we need to add an extra reason code for these 'virtual beds'. At the minute if we take it OOC in our system, it needs a reason for it. If we use the single occ. reason, it will report it back to you. Sunny seemed to want a Single Occupancy - Reserved. Could that be added your side as an acceptable reason for OOC?

**Comment by chrisns** [comment]
@j1a1c1k sure, is 'reserved' the right terminology?

**Comment by j1a1c1k** [comment]
@chrisns From my angle I think it is - we're reserving space for single occupancy by taking a bed out of commission. Probably just worth checking it with Sunny though as ultimately they're the ones reading the reasons. From a centre perspective they won't really even see this as we're just creating ghost beds in the background.

**Comment by chrisns** [comment]
@j1a1c1k I have updated to reflect that, are you happy with this now?
I'm waiting on confirmation that 'reserved' is the correct universal terminology, but it'll only be the only thing to change

**Comment by chrisns** [comment]
@j1a1c1k heard back, confirmed that "reserved" is the correct terminology

**Review by j1a1c1k — APPROVED** [review]

**Comment by j1a1c1k** [comment]
Happy with that - approved it.

**Pull request merged**
