### PR TITLE
#BM-248 Require a reason for intersite moves

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Comment by j1a1c1k** [comment]
Guys, if you don't object I think we need to make sure that the reason is a dropdown list of pre-agreed reasons why an inter-site might occur, then an other category to captcher anything not covered.

The reason I suggest this, is if we have free text entry a DCO could enter a reason which re-classifies the data to greater than OFFICIAL. e.g. a DCO could enter a reason such as DetaineeName1 assaulted DetaineeName2. This then identifies detainees by name and therefore causes us data classification issues.

Can we agree with both inter-site moves and reason for a bed being out of commission that we are limited to a drop-down box with pre-defined reasons? Depmu would then need to contact the centre directly if they needed more info than the summary selected from the dropdown.

**Comment by chrisns** [comment]
@j1a1c1k yes, that sounds sane, could you suggest an enum we can use?

**Comment by j1a1c1k** [comment]
@chrisns I will contact the relevant departments to get a limited list of reasons they regularly use and then feed them back to you. Probably then want to get Sunny to confirm he's happy with that list and let him add/consolidate if he wants to.

**Comment by chrisns** [comment]
cool, are you happy merge this now and circle back when it changes to an enum for another iteration?

**Comment by j1a1c1k** [comment]
Fine with me :)

**Pull request merged**
